// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subStationStatus.proto

package com.pdms.grpc.domain;

public interface AllStationStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.AllStationStatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
