// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subStationStatus.proto

package com.pdms.grpc.domain;

/**
 * <pre>
 *全站响应结果定义
 * </pre>
 *
 * Protobuf type {@code domain.AllStationStatusReply}
 */
public final class AllStationStatusReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.AllStationStatusReply)
    AllStationStatusReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllStationStatusReply.newBuilder() to construct.
  private AllStationStatusReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllStationStatusReply() {
    onlineRate_ = "";
    mmsRate_ = "";
    gooseRate_ = "";
    smvRate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AllStationStatusReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllStationStatusReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            onlineRate_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            mmsRate_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            gooseRate_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            smvRate_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pdms.grpc.domain.SubStationStatusProto.internal_static_domain_AllStationStatusReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pdms.grpc.domain.SubStationStatusProto.internal_static_domain_AllStationStatusReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pdms.grpc.domain.AllStationStatusReply.class, com.pdms.grpc.domain.AllStationStatusReply.Builder.class);
  }

  public static final int ONLINERATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object onlineRate_;
  /**
   * <pre>
   *在线率
   * </pre>
   *
   * <code>string onlineRate = 1;</code>
   * @return The onlineRate.
   */
  @java.lang.Override
  public java.lang.String getOnlineRate() {
    java.lang.Object ref = onlineRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      onlineRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *在线率
   * </pre>
   *
   * <code>string onlineRate = 1;</code>
   * @return The bytes for onlineRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOnlineRateBytes() {
    java.lang.Object ref = onlineRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      onlineRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MMSRATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object mmsRate_;
  /**
   * <pre>
   *MMS通信率
   * </pre>
   *
   * <code>string mmsRate = 2;</code>
   * @return The mmsRate.
   */
  @java.lang.Override
  public java.lang.String getMmsRate() {
    java.lang.Object ref = mmsRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mmsRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *MMS通信率
   * </pre>
   *
   * <code>string mmsRate = 2;</code>
   * @return The bytes for mmsRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMmsRateBytes() {
    java.lang.Object ref = mmsRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mmsRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GOOSERATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object gooseRate_;
  /**
   * <pre>
   *GOOSE通信率
   * </pre>
   *
   * <code>string gooseRate = 3;</code>
   * @return The gooseRate.
   */
  @java.lang.Override
  public java.lang.String getGooseRate() {
    java.lang.Object ref = gooseRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gooseRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *GOOSE通信率
   * </pre>
   *
   * <code>string gooseRate = 3;</code>
   * @return The bytes for gooseRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGooseRateBytes() {
    java.lang.Object ref = gooseRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gooseRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SMVRATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object smvRate_;
  /**
   * <pre>
   *SMV通信率
   * </pre>
   *
   * <code>string smvRate = 4;</code>
   * @return The smvRate.
   */
  @java.lang.Override
  public java.lang.String getSmvRate() {
    java.lang.Object ref = smvRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      smvRate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *SMV通信率
   * </pre>
   *
   * <code>string smvRate = 4;</code>
   * @return The bytes for smvRate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSmvRateBytes() {
    java.lang.Object ref = smvRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      smvRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOnlineRateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, onlineRate_);
    }
    if (!getMmsRateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mmsRate_);
    }
    if (!getGooseRateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gooseRate_);
    }
    if (!getSmvRateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, smvRate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOnlineRateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, onlineRate_);
    }
    if (!getMmsRateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mmsRate_);
    }
    if (!getGooseRateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gooseRate_);
    }
    if (!getSmvRateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, smvRate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pdms.grpc.domain.AllStationStatusReply)) {
      return super.equals(obj);
    }
    com.pdms.grpc.domain.AllStationStatusReply other = (com.pdms.grpc.domain.AllStationStatusReply) obj;

    if (!getOnlineRate()
        .equals(other.getOnlineRate())) return false;
    if (!getMmsRate()
        .equals(other.getMmsRate())) return false;
    if (!getGooseRate()
        .equals(other.getGooseRate())) return false;
    if (!getSmvRate()
        .equals(other.getSmvRate())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ONLINERATE_FIELD_NUMBER;
    hash = (53 * hash) + getOnlineRate().hashCode();
    hash = (37 * hash) + MMSRATE_FIELD_NUMBER;
    hash = (53 * hash) + getMmsRate().hashCode();
    hash = (37 * hash) + GOOSERATE_FIELD_NUMBER;
    hash = (53 * hash) + getGooseRate().hashCode();
    hash = (37 * hash) + SMVRATE_FIELD_NUMBER;
    hash = (53 * hash) + getSmvRate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.AllStationStatusReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pdms.grpc.domain.AllStationStatusReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *全站响应结果定义
   * </pre>
   *
   * Protobuf type {@code domain.AllStationStatusReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.AllStationStatusReply)
      com.pdms.grpc.domain.AllStationStatusReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdms.grpc.domain.SubStationStatusProto.internal_static_domain_AllStationStatusReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdms.grpc.domain.SubStationStatusProto.internal_static_domain_AllStationStatusReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdms.grpc.domain.AllStationStatusReply.class, com.pdms.grpc.domain.AllStationStatusReply.Builder.class);
    }

    // Construct using com.pdms.grpc.domain.AllStationStatusReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      onlineRate_ = "";

      mmsRate_ = "";

      gooseRate_ = "";

      smvRate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pdms.grpc.domain.SubStationStatusProto.internal_static_domain_AllStationStatusReply_descriptor;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.AllStationStatusReply getDefaultInstanceForType() {
      return com.pdms.grpc.domain.AllStationStatusReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.pdms.grpc.domain.AllStationStatusReply build() {
      com.pdms.grpc.domain.AllStationStatusReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.AllStationStatusReply buildPartial() {
      com.pdms.grpc.domain.AllStationStatusReply result = new com.pdms.grpc.domain.AllStationStatusReply(this);
      result.onlineRate_ = onlineRate_;
      result.mmsRate_ = mmsRate_;
      result.gooseRate_ = gooseRate_;
      result.smvRate_ = smvRate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pdms.grpc.domain.AllStationStatusReply) {
        return mergeFrom((com.pdms.grpc.domain.AllStationStatusReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pdms.grpc.domain.AllStationStatusReply other) {
      if (other == com.pdms.grpc.domain.AllStationStatusReply.getDefaultInstance()) return this;
      if (!other.getOnlineRate().isEmpty()) {
        onlineRate_ = other.onlineRate_;
        onChanged();
      }
      if (!other.getMmsRate().isEmpty()) {
        mmsRate_ = other.mmsRate_;
        onChanged();
      }
      if (!other.getGooseRate().isEmpty()) {
        gooseRate_ = other.gooseRate_;
        onChanged();
      }
      if (!other.getSmvRate().isEmpty()) {
        smvRate_ = other.smvRate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pdms.grpc.domain.AllStationStatusReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pdms.grpc.domain.AllStationStatusReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object onlineRate_ = "";
    /**
     * <pre>
     *在线率
     * </pre>
     *
     * <code>string onlineRate = 1;</code>
     * @return The onlineRate.
     */
    public java.lang.String getOnlineRate() {
      java.lang.Object ref = onlineRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        onlineRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *在线率
     * </pre>
     *
     * <code>string onlineRate = 1;</code>
     * @return The bytes for onlineRate.
     */
    public com.google.protobuf.ByteString
        getOnlineRateBytes() {
      java.lang.Object ref = onlineRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        onlineRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *在线率
     * </pre>
     *
     * <code>string onlineRate = 1;</code>
     * @param value The onlineRate to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineRate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      onlineRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *在线率
     * </pre>
     *
     * <code>string onlineRate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlineRate() {
      
      onlineRate_ = getDefaultInstance().getOnlineRate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *在线率
     * </pre>
     *
     * <code>string onlineRate = 1;</code>
     * @param value The bytes for onlineRate to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      onlineRate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mmsRate_ = "";
    /**
     * <pre>
     *MMS通信率
     * </pre>
     *
     * <code>string mmsRate = 2;</code>
     * @return The mmsRate.
     */
    public java.lang.String getMmsRate() {
      java.lang.Object ref = mmsRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mmsRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *MMS通信率
     * </pre>
     *
     * <code>string mmsRate = 2;</code>
     * @return The bytes for mmsRate.
     */
    public com.google.protobuf.ByteString
        getMmsRateBytes() {
      java.lang.Object ref = mmsRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mmsRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *MMS通信率
     * </pre>
     *
     * <code>string mmsRate = 2;</code>
     * @param value The mmsRate to set.
     * @return This builder for chaining.
     */
    public Builder setMmsRate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mmsRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *MMS通信率
     * </pre>
     *
     * <code>string mmsRate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMmsRate() {
      
      mmsRate_ = getDefaultInstance().getMmsRate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *MMS通信率
     * </pre>
     *
     * <code>string mmsRate = 2;</code>
     * @param value The bytes for mmsRate to set.
     * @return This builder for chaining.
     */
    public Builder setMmsRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mmsRate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gooseRate_ = "";
    /**
     * <pre>
     *GOOSE通信率
     * </pre>
     *
     * <code>string gooseRate = 3;</code>
     * @return The gooseRate.
     */
    public java.lang.String getGooseRate() {
      java.lang.Object ref = gooseRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gooseRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *GOOSE通信率
     * </pre>
     *
     * <code>string gooseRate = 3;</code>
     * @return The bytes for gooseRate.
     */
    public com.google.protobuf.ByteString
        getGooseRateBytes() {
      java.lang.Object ref = gooseRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gooseRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *GOOSE通信率
     * </pre>
     *
     * <code>string gooseRate = 3;</code>
     * @param value The gooseRate to set.
     * @return This builder for chaining.
     */
    public Builder setGooseRate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gooseRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *GOOSE通信率
     * </pre>
     *
     * <code>string gooseRate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGooseRate() {
      
      gooseRate_ = getDefaultInstance().getGooseRate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *GOOSE通信率
     * </pre>
     *
     * <code>string gooseRate = 3;</code>
     * @param value The bytes for gooseRate to set.
     * @return This builder for chaining.
     */
    public Builder setGooseRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gooseRate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object smvRate_ = "";
    /**
     * <pre>
     *SMV通信率
     * </pre>
     *
     * <code>string smvRate = 4;</code>
     * @return The smvRate.
     */
    public java.lang.String getSmvRate() {
      java.lang.Object ref = smvRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        smvRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *SMV通信率
     * </pre>
     *
     * <code>string smvRate = 4;</code>
     * @return The bytes for smvRate.
     */
    public com.google.protobuf.ByteString
        getSmvRateBytes() {
      java.lang.Object ref = smvRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        smvRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *SMV通信率
     * </pre>
     *
     * <code>string smvRate = 4;</code>
     * @param value The smvRate to set.
     * @return This builder for chaining.
     */
    public Builder setSmvRate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      smvRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *SMV通信率
     * </pre>
     *
     * <code>string smvRate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSmvRate() {
      
      smvRate_ = getDefaultInstance().getSmvRate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *SMV通信率
     * </pre>
     *
     * <code>string smvRate = 4;</code>
     * @param value The bytes for smvRate to set.
     * @return This builder for chaining.
     */
    public Builder setSmvRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      smvRate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:domain.AllStationStatusReply)
  }

  // @@protoc_insertion_point(class_scope:domain.AllStationStatusReply)
  private static final com.pdms.grpc.domain.AllStationStatusReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pdms.grpc.domain.AllStationStatusReply();
  }

  public static com.pdms.grpc.domain.AllStationStatusReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllStationStatusReply>
      PARSER = new com.google.protobuf.AbstractParser<AllStationStatusReply>() {
    @java.lang.Override
    public AllStationStatusReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllStationStatusReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllStationStatusReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllStationStatusReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pdms.grpc.domain.AllStationStatusReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

