// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

package com.pdms.grpc.domain;

public final class DashBoardProto {
  private DashBoardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_GrpcCommonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_GrpcCommonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_GrpcCommonReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_GrpcCommonReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017dashboard.proto\022\006domain\"$\n\021GrpcCommonR" +
      "equest\022\017\n\007request\030\001 \001(\t\" \n\017GrpcCommonRep" +
      "ly\022\r\n\005reply\030\001 \001(\t2Y\n\tDashBoard\022L\n\024GetDas" +
      "hBoardGrpcData\022\031.domain.GrpcCommonReques" +
      "t\032\027.domain.GrpcCommonReply\"\000B(\n\024com.pdms" +
      ".grpc.domainB\016DashBoardProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_domain_GrpcCommonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domain_GrpcCommonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_GrpcCommonRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_domain_GrpcCommonReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_domain_GrpcCommonReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_GrpcCommonReply_descriptor,
        new java.lang.String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
