// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

package com.pdms.grpc.domain;

public interface GrpcCommonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.GrpcCommonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
