// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subStationStatus.proto

package com.pdms.grpc.domain;

public final class SubStationStatusProto {
  private SubStationStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_SubStationStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_SubStationStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_AllStationStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_AllStationStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_AllStationStatusReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_AllStationStatusReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_SubStationStatusReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_SubStationStatusReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026subStationStatus.proto\022\006domain\"/\n\027SubS" +
      "tationStatusRequest\022\024\n\014substationId\030\001 \001(" +
      "\t\"\031\n\027AllStationStatusRequest\"`\n\025AllStati" +
      "onStatusReply\022\022\n\nonlineRate\030\001 \001(\t\022\017\n\007mms" +
      "Rate\030\002 \001(\t\022\021\n\tgooseRate\030\003 \001(\t\022\017\n\007smvRate" +
      "\030\004 \001(\t\"p\n\025SubStationStatusReply\022\022\n\nonlin" +
      "eRate\030\001 \001(\t\022\017\n\007mmsRate\030\002 \001(\t\022\021\n\tgooseRat" +
      "e\030\003 \001(\t\022\017\n\007smvRate\030\004 \001(\t\022\016\n\006status\030\005 \001(\t" +
      "2\313\001\n\020SubStationStatus\022W\n\023GetStatusStatis" +
      "tics\022\037.domain.SubStationStatusRequest\032\035." +
      "domain.SubStationStatusReply\"\000\022^\n\032GetAll" +
      "StationStatusRequest\022\037.domain.AllStation" +
      "StatusRequest\032\035.domain.AllStationStatusR" +
      "eply\"\000B/\n\024com.pdms.grpc.domainB\025SubStati" +
      "onStatusProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_domain_SubStationStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domain_SubStationStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_SubStationStatusRequest_descriptor,
        new java.lang.String[] { "SubstationId", });
    internal_static_domain_AllStationStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_domain_AllStationStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_AllStationStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_domain_AllStationStatusReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_domain_AllStationStatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_AllStationStatusReply_descriptor,
        new java.lang.String[] { "OnlineRate", "MmsRate", "GooseRate", "SmvRate", });
    internal_static_domain_SubStationStatusReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_domain_SubStationStatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_SubStationStatusReply_descriptor,
        new java.lang.String[] { "OnlineRate", "MmsRate", "GooseRate", "SmvRate", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
