// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subStationStatus.proto

package com.pdms.grpc.domain;

public interface SubStationStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.SubStationStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string substationId = 1;</code>
   * @return The substationId.
   */
  java.lang.String getSubstationId();
  /**
   * <code>string substationId = 1;</code>
   * @return The bytes for substationId.
   */
  com.google.protobuf.ByteString
      getSubstationIdBytes();
}
