// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitation.proto

package com.pdms.grpc.domain;

public interface VisitationReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.VisitationReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *巡视率
   * </pre>
   *
   * <code>string visitationRate = 1;</code>
   * @return The visitationRate.
   */
  java.lang.String getVisitationRate();
  /**
   * <pre>
   *巡视率
   * </pre>
   *
   * <code>string visitationRate = 1;</code>
   * @return The bytes for visitationRate.
   */
  com.google.protobuf.ByteString
      getVisitationRateBytes();
}
