// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warning.proto

package com.pdms.grpc.domain;

public interface WarningListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.WarningListReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  java.util.List<com.pdms.grpc.domain.WarningItemReply> 
      getReplyList();
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  com.pdms.grpc.domain.WarningItemReply getReply(int index);
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  int getReplyCount();
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  java.util.List<? extends com.pdms.grpc.domain.WarningItemReplyOrBuilder> 
      getReplyOrBuilderList();
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  com.pdms.grpc.domain.WarningItemReplyOrBuilder getReplyOrBuilder(
      int index);
}
