// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warning.proto

package com.pdms.grpc.domain;

/**
 * Protobuf type {@code domain.WarningListReply}
 */
public final class WarningListReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.WarningListReply)
    WarningListReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WarningListReply.newBuilder() to construct.
  private WarningListReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WarningListReply() {
    reply_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WarningListReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WarningListReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reply_ = new java.util.ArrayList<com.pdms.grpc.domain.WarningItemReply>();
              mutable_bitField0_ |= 0x00000001;
            }
            reply_.add(
                input.readMessage(com.pdms.grpc.domain.WarningItemReply.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reply_ = java.util.Collections.unmodifiableList(reply_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningListReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningListReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pdms.grpc.domain.WarningListReply.class, com.pdms.grpc.domain.WarningListReply.Builder.class);
  }

  public static final int REPLY_FIELD_NUMBER = 1;
  private java.util.List<com.pdms.grpc.domain.WarningItemReply> reply_;
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.pdms.grpc.domain.WarningItemReply> getReplyList() {
    return reply_;
  }
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.pdms.grpc.domain.WarningItemReplyOrBuilder> 
      getReplyOrBuilderList() {
    return reply_;
  }
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  @java.lang.Override
  public int getReplyCount() {
    return reply_.size();
  }
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  @java.lang.Override
  public com.pdms.grpc.domain.WarningItemReply getReply(int index) {
    return reply_.get(index);
  }
  /**
   * <code>repeated .domain.WarningItemReply reply = 1;</code>
   */
  @java.lang.Override
  public com.pdms.grpc.domain.WarningItemReplyOrBuilder getReplyOrBuilder(
      int index) {
    return reply_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < reply_.size(); i++) {
      output.writeMessage(1, reply_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < reply_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, reply_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pdms.grpc.domain.WarningListReply)) {
      return super.equals(obj);
    }
    com.pdms.grpc.domain.WarningListReply other = (com.pdms.grpc.domain.WarningListReply) obj;

    if (!getReplyList()
        .equals(other.getReplyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReplyCount() > 0) {
      hash = (37 * hash) + REPLY_FIELD_NUMBER;
      hash = (53 * hash) + getReplyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningListReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningListReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningListReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pdms.grpc.domain.WarningListReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code domain.WarningListReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.WarningListReply)
      com.pdms.grpc.domain.WarningListReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningListReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningListReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdms.grpc.domain.WarningListReply.class, com.pdms.grpc.domain.WarningListReply.Builder.class);
    }

    // Construct using com.pdms.grpc.domain.WarningListReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReplyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (replyBuilder_ == null) {
        reply_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        replyBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningListReply_descriptor;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningListReply getDefaultInstanceForType() {
      return com.pdms.grpc.domain.WarningListReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningListReply build() {
      com.pdms.grpc.domain.WarningListReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningListReply buildPartial() {
      com.pdms.grpc.domain.WarningListReply result = new com.pdms.grpc.domain.WarningListReply(this);
      int from_bitField0_ = bitField0_;
      if (replyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          reply_ = java.util.Collections.unmodifiableList(reply_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reply_ = reply_;
      } else {
        result.reply_ = replyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pdms.grpc.domain.WarningListReply) {
        return mergeFrom((com.pdms.grpc.domain.WarningListReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pdms.grpc.domain.WarningListReply other) {
      if (other == com.pdms.grpc.domain.WarningListReply.getDefaultInstance()) return this;
      if (replyBuilder_ == null) {
        if (!other.reply_.isEmpty()) {
          if (reply_.isEmpty()) {
            reply_ = other.reply_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReplyIsMutable();
            reply_.addAll(other.reply_);
          }
          onChanged();
        }
      } else {
        if (!other.reply_.isEmpty()) {
          if (replyBuilder_.isEmpty()) {
            replyBuilder_.dispose();
            replyBuilder_ = null;
            reply_ = other.reply_;
            bitField0_ = (bitField0_ & ~0x00000001);
            replyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReplyFieldBuilder() : null;
          } else {
            replyBuilder_.addAllMessages(other.reply_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pdms.grpc.domain.WarningListReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pdms.grpc.domain.WarningListReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.pdms.grpc.domain.WarningItemReply> reply_ =
      java.util.Collections.emptyList();
    private void ensureReplyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reply_ = new java.util.ArrayList<com.pdms.grpc.domain.WarningItemReply>(reply_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pdms.grpc.domain.WarningItemReply, com.pdms.grpc.domain.WarningItemReply.Builder, com.pdms.grpc.domain.WarningItemReplyOrBuilder> replyBuilder_;

    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public java.util.List<com.pdms.grpc.domain.WarningItemReply> getReplyList() {
      if (replyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reply_);
      } else {
        return replyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public int getReplyCount() {
      if (replyBuilder_ == null) {
        return reply_.size();
      } else {
        return replyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public com.pdms.grpc.domain.WarningItemReply getReply(int index) {
      if (replyBuilder_ == null) {
        return reply_.get(index);
      } else {
        return replyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder setReply(
        int index, com.pdms.grpc.domain.WarningItemReply value) {
      if (replyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplyIsMutable();
        reply_.set(index, value);
        onChanged();
      } else {
        replyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder setReply(
        int index, com.pdms.grpc.domain.WarningItemReply.Builder builderForValue) {
      if (replyBuilder_ == null) {
        ensureReplyIsMutable();
        reply_.set(index, builderForValue.build());
        onChanged();
      } else {
        replyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder addReply(com.pdms.grpc.domain.WarningItemReply value) {
      if (replyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplyIsMutable();
        reply_.add(value);
        onChanged();
      } else {
        replyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder addReply(
        int index, com.pdms.grpc.domain.WarningItemReply value) {
      if (replyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplyIsMutable();
        reply_.add(index, value);
        onChanged();
      } else {
        replyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder addReply(
        com.pdms.grpc.domain.WarningItemReply.Builder builderForValue) {
      if (replyBuilder_ == null) {
        ensureReplyIsMutable();
        reply_.add(builderForValue.build());
        onChanged();
      } else {
        replyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder addReply(
        int index, com.pdms.grpc.domain.WarningItemReply.Builder builderForValue) {
      if (replyBuilder_ == null) {
        ensureReplyIsMutable();
        reply_.add(index, builderForValue.build());
        onChanged();
      } else {
        replyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder addAllReply(
        java.lang.Iterable<? extends com.pdms.grpc.domain.WarningItemReply> values) {
      if (replyBuilder_ == null) {
        ensureReplyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reply_);
        onChanged();
      } else {
        replyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder clearReply() {
      if (replyBuilder_ == null) {
        reply_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        replyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public Builder removeReply(int index) {
      if (replyBuilder_ == null) {
        ensureReplyIsMutable();
        reply_.remove(index);
        onChanged();
      } else {
        replyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public com.pdms.grpc.domain.WarningItemReply.Builder getReplyBuilder(
        int index) {
      return getReplyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public com.pdms.grpc.domain.WarningItemReplyOrBuilder getReplyOrBuilder(
        int index) {
      if (replyBuilder_ == null) {
        return reply_.get(index);  } else {
        return replyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public java.util.List<? extends com.pdms.grpc.domain.WarningItemReplyOrBuilder> 
         getReplyOrBuilderList() {
      if (replyBuilder_ != null) {
        return replyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reply_);
      }
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public com.pdms.grpc.domain.WarningItemReply.Builder addReplyBuilder() {
      return getReplyFieldBuilder().addBuilder(
          com.pdms.grpc.domain.WarningItemReply.getDefaultInstance());
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public com.pdms.grpc.domain.WarningItemReply.Builder addReplyBuilder(
        int index) {
      return getReplyFieldBuilder().addBuilder(
          index, com.pdms.grpc.domain.WarningItemReply.getDefaultInstance());
    }
    /**
     * <code>repeated .domain.WarningItemReply reply = 1;</code>
     */
    public java.util.List<com.pdms.grpc.domain.WarningItemReply.Builder> 
         getReplyBuilderList() {
      return getReplyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.pdms.grpc.domain.WarningItemReply, com.pdms.grpc.domain.WarningItemReply.Builder, com.pdms.grpc.domain.WarningItemReplyOrBuilder> 
        getReplyFieldBuilder() {
      if (replyBuilder_ == null) {
        replyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.pdms.grpc.domain.WarningItemReply, com.pdms.grpc.domain.WarningItemReply.Builder, com.pdms.grpc.domain.WarningItemReplyOrBuilder>(
                reply_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        reply_ = null;
      }
      return replyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:domain.WarningListReply)
  }

  // @@protoc_insertion_point(class_scope:domain.WarningListReply)
  private static final com.pdms.grpc.domain.WarningListReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pdms.grpc.domain.WarningListReply();
  }

  public static com.pdms.grpc.domain.WarningListReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WarningListReply>
      PARSER = new com.google.protobuf.AbstractParser<WarningListReply>() {
    @java.lang.Override
    public WarningListReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WarningListReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WarningListReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WarningListReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pdms.grpc.domain.WarningListReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

