// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warning.proto

package com.pdms.grpc.domain;

public interface WarningAndLockReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.WarningAndLockReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *告警条数
   * </pre>
   *
   * <code>string warningNumber = 1;</code>
   * @return The warningNumber.
   */
  java.lang.String getWarningNumber();
  /**
   * <pre>
   *告警条数
   * </pre>
   *
   * <code>string warningNumber = 1;</code>
   * @return The bytes for warningNumber.
   */
  com.google.protobuf.ByteString
      getWarningNumberBytes();

  /**
   * <pre>
   *闭锁条数
   * </pre>
   *
   * <code>string lockNumber = 2;</code>
   * @return The lockNumber.
   */
  java.lang.String getLockNumber();
  /**
   * <pre>
   *闭锁条数
   * </pre>
   *
   * <code>string lockNumber = 2;</code>
   * @return The bytes for lockNumber.
   */
  com.google.protobuf.ByteString
      getLockNumberBytes();

  /**
   * <pre>
   *保护状态统计
   * </pre>
   *
   * <code>string procStatusNumber = 3;</code>
   * @return The procStatusNumber.
   */
  java.lang.String getProcStatusNumber();
  /**
   * <pre>
   *保护状态统计
   * </pre>
   *
   * <code>string procStatusNumber = 3;</code>
   * @return The bytes for procStatusNumber.
   */
  com.google.protobuf.ByteString
      getProcStatusNumberBytes();
}
