// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warning.proto

package com.pdms.grpc.domain;

/**
 * <pre>
 *站所告警统计列表响应结果定义
 * </pre>
 *
 * Protobuf type {@code domain.WarningItemReply}
 */
public final class WarningItemReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.WarningItemReply)
    WarningItemReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WarningItemReply.newBuilder() to construct.
  private WarningItemReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WarningItemReply() {
    stationName_ = "";
    type_ = "";
    warningNumber_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WarningItemReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WarningItemReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            stationName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            warningNumber_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningItemReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningItemReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pdms.grpc.domain.WarningItemReply.class, com.pdms.grpc.domain.WarningItemReply.Builder.class);
  }

  public static final int STATIONNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object stationName_;
  /**
   * <pre>
   *站所名称
   * </pre>
   *
   * <code>string stationName = 1;</code>
   * @return The stationName.
   */
  @java.lang.Override
  public java.lang.String getStationName() {
    java.lang.Object ref = stationName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stationName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *站所名称
   * </pre>
   *
   * <code>string stationName = 1;</code>
   * @return The bytes for stationName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStationNameBytes() {
    java.lang.Object ref = stationName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   *告警分类
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *告警分类
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WARNINGNUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object warningNumber_;
  /**
   * <pre>
   *告警数量
   * </pre>
   *
   * <code>string warningNumber = 3;</code>
   * @return The warningNumber.
   */
  @java.lang.Override
  public java.lang.String getWarningNumber() {
    java.lang.Object ref = warningNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      warningNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *告警数量
   * </pre>
   *
   * <code>string warningNumber = 3;</code>
   * @return The bytes for warningNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWarningNumberBytes() {
    java.lang.Object ref = warningNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      warningNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStationNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stationName_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (!getWarningNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, warningNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStationNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stationName_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (!getWarningNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, warningNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pdms.grpc.domain.WarningItemReply)) {
      return super.equals(obj);
    }
    com.pdms.grpc.domain.WarningItemReply other = (com.pdms.grpc.domain.WarningItemReply) obj;

    if (!getStationName()
        .equals(other.getStationName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getWarningNumber()
        .equals(other.getWarningNumber())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStationName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + WARNINGNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getWarningNumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningItemReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pdms.grpc.domain.WarningItemReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *站所告警统计列表响应结果定义
   * </pre>
   *
   * Protobuf type {@code domain.WarningItemReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.WarningItemReply)
      com.pdms.grpc.domain.WarningItemReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningItemReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningItemReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdms.grpc.domain.WarningItemReply.class, com.pdms.grpc.domain.WarningItemReply.Builder.class);
    }

    // Construct using com.pdms.grpc.domain.WarningItemReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stationName_ = "";

      type_ = "";

      warningNumber_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningItemReply_descriptor;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningItemReply getDefaultInstanceForType() {
      return com.pdms.grpc.domain.WarningItemReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningItemReply build() {
      com.pdms.grpc.domain.WarningItemReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningItemReply buildPartial() {
      com.pdms.grpc.domain.WarningItemReply result = new com.pdms.grpc.domain.WarningItemReply(this);
      result.stationName_ = stationName_;
      result.type_ = type_;
      result.warningNumber_ = warningNumber_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pdms.grpc.domain.WarningItemReply) {
        return mergeFrom((com.pdms.grpc.domain.WarningItemReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pdms.grpc.domain.WarningItemReply other) {
      if (other == com.pdms.grpc.domain.WarningItemReply.getDefaultInstance()) return this;
      if (!other.getStationName().isEmpty()) {
        stationName_ = other.stationName_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getWarningNumber().isEmpty()) {
        warningNumber_ = other.warningNumber_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pdms.grpc.domain.WarningItemReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pdms.grpc.domain.WarningItemReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object stationName_ = "";
    /**
     * <pre>
     *站所名称
     * </pre>
     *
     * <code>string stationName = 1;</code>
     * @return The stationName.
     */
    public java.lang.String getStationName() {
      java.lang.Object ref = stationName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *站所名称
     * </pre>
     *
     * <code>string stationName = 1;</code>
     * @return The bytes for stationName.
     */
    public com.google.protobuf.ByteString
        getStationNameBytes() {
      java.lang.Object ref = stationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *站所名称
     * </pre>
     *
     * <code>string stationName = 1;</code>
     * @param value The stationName to set.
     * @return This builder for chaining.
     */
    public Builder setStationName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stationName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *站所名称
     * </pre>
     *
     * <code>string stationName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStationName() {
      
      stationName_ = getDefaultInstance().getStationName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *站所名称
     * </pre>
     *
     * <code>string stationName = 1;</code>
     * @param value The bytes for stationName to set.
     * @return This builder for chaining.
     */
    public Builder setStationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stationName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     *告警分类
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *告警分类
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *告警分类
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告警分类
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告警分类
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object warningNumber_ = "";
    /**
     * <pre>
     *告警数量
     * </pre>
     *
     * <code>string warningNumber = 3;</code>
     * @return The warningNumber.
     */
    public java.lang.String getWarningNumber() {
      java.lang.Object ref = warningNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        warningNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *告警数量
     * </pre>
     *
     * <code>string warningNumber = 3;</code>
     * @return The bytes for warningNumber.
     */
    public com.google.protobuf.ByteString
        getWarningNumberBytes() {
      java.lang.Object ref = warningNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        warningNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *告警数量
     * </pre>
     *
     * <code>string warningNumber = 3;</code>
     * @param value The warningNumber to set.
     * @return This builder for chaining.
     */
    public Builder setWarningNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      warningNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告警数量
     * </pre>
     *
     * <code>string warningNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarningNumber() {
      
      warningNumber_ = getDefaultInstance().getWarningNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告警数量
     * </pre>
     *
     * <code>string warningNumber = 3;</code>
     * @param value The bytes for warningNumber to set.
     * @return This builder for chaining.
     */
    public Builder setWarningNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      warningNumber_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:domain.WarningItemReply)
  }

  // @@protoc_insertion_point(class_scope:domain.WarningItemReply)
  private static final com.pdms.grpc.domain.WarningItemReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pdms.grpc.domain.WarningItemReply();
  }

  public static com.pdms.grpc.domain.WarningItemReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WarningItemReply>
      PARSER = new com.google.protobuf.AbstractParser<WarningItemReply>() {
    @java.lang.Override
    public WarningItemReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WarningItemReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WarningItemReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WarningItemReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pdms.grpc.domain.WarningItemReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

