// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warning.proto

package com.pdms.grpc.domain;

public interface WarningListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.WarningListRequest)
    com.google.protobuf.MessageOrBuilder {
}
