// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warning.proto

package com.pdms.grpc.domain;

/**
 * <pre>
 *响应结果定义
 * </pre>
 *
 * Protobuf type {@code domain.WarningAndLockReply}
 */
public final class WarningAndLockReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.WarningAndLockReply)
    WarningAndLockReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WarningAndLockReply.newBuilder() to construct.
  private WarningAndLockReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WarningAndLockReply() {
    warningNumber_ = "";
    lockNumber_ = "";
    procStatusNumber_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WarningAndLockReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WarningAndLockReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            warningNumber_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            lockNumber_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            procStatusNumber_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningAndLockReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningAndLockReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pdms.grpc.domain.WarningAndLockReply.class, com.pdms.grpc.domain.WarningAndLockReply.Builder.class);
  }

  public static final int WARNINGNUMBER_FIELD_NUMBER = 1;
  private volatile java.lang.Object warningNumber_;
  /**
   * <pre>
   *告警条数
   * </pre>
   *
   * <code>string warningNumber = 1;</code>
   * @return The warningNumber.
   */
  @java.lang.Override
  public java.lang.String getWarningNumber() {
    java.lang.Object ref = warningNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      warningNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *告警条数
   * </pre>
   *
   * <code>string warningNumber = 1;</code>
   * @return The bytes for warningNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWarningNumberBytes() {
    java.lang.Object ref = warningNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      warningNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCKNUMBER_FIELD_NUMBER = 2;
  private volatile java.lang.Object lockNumber_;
  /**
   * <pre>
   *闭锁条数
   * </pre>
   *
   * <code>string lockNumber = 2;</code>
   * @return The lockNumber.
   */
  @java.lang.Override
  public java.lang.String getLockNumber() {
    java.lang.Object ref = lockNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lockNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *闭锁条数
   * </pre>
   *
   * <code>string lockNumber = 2;</code>
   * @return The bytes for lockNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLockNumberBytes() {
    java.lang.Object ref = lockNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lockNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCSTATUSNUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object procStatusNumber_;
  /**
   * <pre>
   *保护状态统计
   * </pre>
   *
   * <code>string procStatusNumber = 3;</code>
   * @return The procStatusNumber.
   */
  @java.lang.Override
  public java.lang.String getProcStatusNumber() {
    java.lang.Object ref = procStatusNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      procStatusNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *保护状态统计
   * </pre>
   *
   * <code>string procStatusNumber = 3;</code>
   * @return The bytes for procStatusNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcStatusNumberBytes() {
    java.lang.Object ref = procStatusNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      procStatusNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWarningNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, warningNumber_);
    }
    if (!getLockNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lockNumber_);
    }
    if (!getProcStatusNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, procStatusNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWarningNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, warningNumber_);
    }
    if (!getLockNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lockNumber_);
    }
    if (!getProcStatusNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, procStatusNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pdms.grpc.domain.WarningAndLockReply)) {
      return super.equals(obj);
    }
    com.pdms.grpc.domain.WarningAndLockReply other = (com.pdms.grpc.domain.WarningAndLockReply) obj;

    if (!getWarningNumber()
        .equals(other.getWarningNumber())) return false;
    if (!getLockNumber()
        .equals(other.getLockNumber())) return false;
    if (!getProcStatusNumber()
        .equals(other.getProcStatusNumber())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WARNINGNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getWarningNumber().hashCode();
    hash = (37 * hash) + LOCKNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLockNumber().hashCode();
    hash = (37 * hash) + PROCSTATUSNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getProcStatusNumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pdms.grpc.domain.WarningAndLockReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pdms.grpc.domain.WarningAndLockReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *响应结果定义
   * </pre>
   *
   * Protobuf type {@code domain.WarningAndLockReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.WarningAndLockReply)
      com.pdms.grpc.domain.WarningAndLockReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningAndLockReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningAndLockReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pdms.grpc.domain.WarningAndLockReply.class, com.pdms.grpc.domain.WarningAndLockReply.Builder.class);
    }

    // Construct using com.pdms.grpc.domain.WarningAndLockReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      warningNumber_ = "";

      lockNumber_ = "";

      procStatusNumber_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pdms.grpc.domain.WarningProto.internal_static_domain_WarningAndLockReply_descriptor;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningAndLockReply getDefaultInstanceForType() {
      return com.pdms.grpc.domain.WarningAndLockReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningAndLockReply build() {
      com.pdms.grpc.domain.WarningAndLockReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pdms.grpc.domain.WarningAndLockReply buildPartial() {
      com.pdms.grpc.domain.WarningAndLockReply result = new com.pdms.grpc.domain.WarningAndLockReply(this);
      result.warningNumber_ = warningNumber_;
      result.lockNumber_ = lockNumber_;
      result.procStatusNumber_ = procStatusNumber_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pdms.grpc.domain.WarningAndLockReply) {
        return mergeFrom((com.pdms.grpc.domain.WarningAndLockReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pdms.grpc.domain.WarningAndLockReply other) {
      if (other == com.pdms.grpc.domain.WarningAndLockReply.getDefaultInstance()) return this;
      if (!other.getWarningNumber().isEmpty()) {
        warningNumber_ = other.warningNumber_;
        onChanged();
      }
      if (!other.getLockNumber().isEmpty()) {
        lockNumber_ = other.lockNumber_;
        onChanged();
      }
      if (!other.getProcStatusNumber().isEmpty()) {
        procStatusNumber_ = other.procStatusNumber_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.pdms.grpc.domain.WarningAndLockReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.pdms.grpc.domain.WarningAndLockReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object warningNumber_ = "";
    /**
     * <pre>
     *告警条数
     * </pre>
     *
     * <code>string warningNumber = 1;</code>
     * @return The warningNumber.
     */
    public java.lang.String getWarningNumber() {
      java.lang.Object ref = warningNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        warningNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *告警条数
     * </pre>
     *
     * <code>string warningNumber = 1;</code>
     * @return The bytes for warningNumber.
     */
    public com.google.protobuf.ByteString
        getWarningNumberBytes() {
      java.lang.Object ref = warningNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        warningNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *告警条数
     * </pre>
     *
     * <code>string warningNumber = 1;</code>
     * @param value The warningNumber to set.
     * @return This builder for chaining.
     */
    public Builder setWarningNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      warningNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告警条数
     * </pre>
     *
     * <code>string warningNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarningNumber() {
      
      warningNumber_ = getDefaultInstance().getWarningNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *告警条数
     * </pre>
     *
     * <code>string warningNumber = 1;</code>
     * @param value The bytes for warningNumber to set.
     * @return This builder for chaining.
     */
    public Builder setWarningNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      warningNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lockNumber_ = "";
    /**
     * <pre>
     *闭锁条数
     * </pre>
     *
     * <code>string lockNumber = 2;</code>
     * @return The lockNumber.
     */
    public java.lang.String getLockNumber() {
      java.lang.Object ref = lockNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lockNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *闭锁条数
     * </pre>
     *
     * <code>string lockNumber = 2;</code>
     * @return The bytes for lockNumber.
     */
    public com.google.protobuf.ByteString
        getLockNumberBytes() {
      java.lang.Object ref = lockNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lockNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *闭锁条数
     * </pre>
     *
     * <code>string lockNumber = 2;</code>
     * @param value The lockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setLockNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lockNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *闭锁条数
     * </pre>
     *
     * <code>string lockNumber = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLockNumber() {
      
      lockNumber_ = getDefaultInstance().getLockNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *闭锁条数
     * </pre>
     *
     * <code>string lockNumber = 2;</code>
     * @param value The bytes for lockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setLockNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lockNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object procStatusNumber_ = "";
    /**
     * <pre>
     *保护状态统计
     * </pre>
     *
     * <code>string procStatusNumber = 3;</code>
     * @return The procStatusNumber.
     */
    public java.lang.String getProcStatusNumber() {
      java.lang.Object ref = procStatusNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        procStatusNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *保护状态统计
     * </pre>
     *
     * <code>string procStatusNumber = 3;</code>
     * @return The bytes for procStatusNumber.
     */
    public com.google.protobuf.ByteString
        getProcStatusNumberBytes() {
      java.lang.Object ref = procStatusNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        procStatusNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *保护状态统计
     * </pre>
     *
     * <code>string procStatusNumber = 3;</code>
     * @param value The procStatusNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProcStatusNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      procStatusNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *保护状态统计
     * </pre>
     *
     * <code>string procStatusNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcStatusNumber() {
      
      procStatusNumber_ = getDefaultInstance().getProcStatusNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *保护状态统计
     * </pre>
     *
     * <code>string procStatusNumber = 3;</code>
     * @param value The bytes for procStatusNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProcStatusNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      procStatusNumber_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:domain.WarningAndLockReply)
  }

  // @@protoc_insertion_point(class_scope:domain.WarningAndLockReply)
  private static final com.pdms.grpc.domain.WarningAndLockReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pdms.grpc.domain.WarningAndLockReply();
  }

  public static com.pdms.grpc.domain.WarningAndLockReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WarningAndLockReply>
      PARSER = new com.google.protobuf.AbstractParser<WarningAndLockReply>() {
    @java.lang.Override
    public WarningAndLockReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WarningAndLockReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WarningAndLockReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WarningAndLockReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pdms.grpc.domain.WarningAndLockReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

