version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    container_name: minio
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - TZ=Asia/Shanghai
    volumes:
      - ${GRIDNT_IOT_DEPLOY_BASE}/iot/data/minio/data_server:/data
      - ${GRIDNT_IOT_DEPLOY_BASE}/iot/data/minio/data_server_config:/root/.minio
    ports:
      - 9000:9000
    command: server /data
    restart: always
    networks:
      - custom_net
networks:
  custom_net:
    external:
      name: pomd-web
